version: "3.9"

services:
  redis:
    image: bitnami/redis:7.0
    ports:
      - "6379:6379"
    restart: on-failure
    env_file:
      - .env
    profiles:
      - dev
  db:
    image: mysql:8
    env_file:
      - .env
    restart: on-failure
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - ./.volumes/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    profiles:
      - dev
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8888:80"
    restart: on-failure
    environment:
      PMA_HOST: db
    profiles:
      - debug


